---

- name: SFTP
  hosts: all
#  vars_files:
#    - inputs.yml
  become: true
  become_user: root

 
  tasks:
  
    - name: Ensure groups exists
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - local-sftp-users
        - sftp-shares-with-mediation
  
    - name: Create sftp user with mediation flow
      user:
        name: "{{ username }}"
        groups: "sftp-shares-with-mediation"
        shell:  "/sbin/nologin"
        comment: "{{ comment }}"
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create
        append: yes
      when: mediation_flow == "yes"


    - name: Create sftp user without mediation
      user:
        name: "{{ username }}"
        groups: "local-sftp-users"
        shell:  "/sbin/nologin"
        comment: "{{ comment }}"
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create
        append: yes
      when: mediation_flow == "no"


#    - name: Set 365 maximum expiration date for password
#      user:
#        name: "{{item.name}}"
#        password_expire_max: 365
#      with_items: "{{ sftp_users }}"

    - name: Create a directory for sftp users if it does not exist (Mediation Flow)
      file:
        path: "/sftp_home/group_shares/sftp-mediation/{{ username }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      when: mediation_flow == "yes"


    - name: Create a directory for sftp users if it does not exist
      file:
        path: "/sftp_home/group_shares/{{ username }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      when: mediation_flow == "no"

    - name: Creating SFTP dir for Jail 
      file:
        path: /sftp_home/group_shares/sftp-mediation/{{ username }}/{{ item }}
        state: directory
        owner: "sftp-mediation"
        group: "{{ username }}"
        mode: u=rwx,g+rwxs,o-rwx
      with_items:
        - "{{ folders }}"      
      when: mediation_flow == "yes"

    - name: Creating SFTP dir for Jail (No Mediation)
      file:
        path: /sftp_home/group_shares/{{ username }}/{{ item }}
        state: directory
        owner: root
        group: "{{ username }}"
        mode: u=rwx,g+rwxs,o-rwx
      with_items:
        - "{{ folders }}"
      when: mediation_flow == "no"
